name: test_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  animated_splash_screen: ^1.3.0
  shared_preferences: ^2.0.16
  http: ^0.13.5
  flutter_svg: ^1.1.6
  expansion_tile_card: ^2.0.0
  lottie: ^2.2.0
  dartz: ^0.10.1
  dio: ^5.0.0
  google_maps_flutter:
    git:
      url: https://github.com/lukaskurz/plugins
      path: packages/google_maps_flutter/google_maps_flutter
      ref: main
  rename: ^2.1.1



dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
  geolocator: ^7.7.1
  geocoding: ^2.0.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/asset 10.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/icons/
    - assets/image/json/

  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
        - asset: assets/Fonts/Poppins-Medium.ttf
        - asset: assets/Fonts/Poppins-Regular.ttf
          weight: 700
